name: Deploy

on: push

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - name: Use node
      
        uses: actions/setup-node@v3
        with:
          node-version: 16 
             
      - name: Install dependecies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "online-opcina-travnik" 
          heroku_email: "seferovicisa@gmail.com"
 
    
      
